# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '54.179.205.134'
    sshKeySecureFile: 'id_rsa_z8_lightsail_no_password'
- task: SSH@0
  inputs:
    sshEndpoint: 'SSH TEST env 54.179.205.134'
    runOptions: 'commands'
    commands: |
      sudo git --git-dir=./zen8/iCare/.git pull
      cd zen8/ && sudo ./restart.sh
    readyTimeout: '20000'
    failOnStdErr: false
