version: "2"
services:
  db:
    image: postgres:15
    container_name: icare_db
    user: root
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022
      - POSTGRES_DB=postgres
    restart: always # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  odoo17:
    image: odoo:17
    container_name: icare_app
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072" # live chat
    tty: true
    # command: -u zen8_module -d icare-obs --max-cron-threads=0 --stop-after-init --no-xmlrpc
    environment:
      - HOST=icare_db
      - USER=odoo
      - PASSWORD=odoo16@2022
    volumes:
      - ./z_addons:/mnt/extra-addons
      - ./logs:/var/log/odoo/
      - ./config:/etc/odoo
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/entrypoint.sh" ]
